# Generated by Django 4.1.4 on 2023-01-16 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(blank=True, verbose_name='Текст статьи')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('video', models.FileField(upload_to='uploads/', verbose_name='Видео')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('rating', models.SmallIntegerField(default=0)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['date_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('tank', 'Танки'), ('heal', 'Хилы'), ('dd', 'ДД'), ('sales', 'Торговцы'), ('gildenmaster', 'Гилдмастеры'), ('guest', 'Квестгиверы, '), ('blacksmiths', 'Кузнецы'), ('skinner', 'Кожевники'), ('potions', 'Зельевары'), ('spell masters', 'Мастера заклинаний')], db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CommentArticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('dateCreation', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('commentArticles', models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, related_name='comments_articles', to='board.articles')),
                ('commentAuthor', models.ForeignKey(default='Free', on_delete=django.db.models.deletion.CASCADE, to='board.author', verbose_name='Автор комментария')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='articles',
            name='cat',
            field=models.ForeignKey(default='1', max_length=15, on_delete=django.db.models.deletion.PROTECT, to='board.category', verbose_name='Категория'),
        ),
    ]
