# Generated by Django 4.1.4 on 2023-01-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='cat',
            field=models.ForeignKey(default='tank', max_length=15, on_delete=django.db.models.deletion.PROTECT, to='board.category', verbose_name='Категория'),
        ),
    ]
